// <auto-generated />
using System;
using Bookify.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookify.Infrastructure.Migrations
{
    [DbContext(typeof(BookifyDbContext))]
    partial class BookifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMerchant", b =>
                {
                    b.Property<Guid>("BooksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MerchantsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BooksId", "MerchantsId");

                    b.HasIndex("MerchantsId");

                    b.ToTable("BookMerchant");
                });

            modelBuilder.Entity("Bookify.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3477e952-c34a-47c7-a3d9-39d136ce486f"),
                            DateOfBirth = new DateTime(1564, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "William Shakespeare",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("2ea49d95-4e4e-44ee-950e-b273c0cbea8a"),
                            FullName = "Charles Dickens",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5a8085ee-1909-446c-8a24-3c3c45ccf9b6"),
                            FullName = "Fyodor Dostoevsky",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("b65902a7-8c44-413a-99bc-86156211ae3b"),
                            FullName = "Ernest Hemingway",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("86902c7c-c31a-4a4f-95e1-3eeca9c39e6e"),
                            DateOfBirth = new DateTime(1848, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hristo Botev",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Bookify.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Bookify.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateFounded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c424a69-42b0-49db-b1a5-7c2e8820e22d"),
                            DateFounded = new DateTime(1994, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = new Guid("d53bfa82-def2-48ad-9cad-0ae619677155"),
                            DateFounded = new DateTime(2008, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Ozone"
                        },
                        new
                        {
                            Id = new Guid("467d5837-8ff7-43ed-abf9-92fd430f4dc8"),
                            DateFounded = new DateTime(1971, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Powell's Books"
                        });
                });

            modelBuilder.Entity("BookMerchant", b =>
                {
                    b.HasOne("Bookify.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookify.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bookify.Entities.Book", b =>
                {
                    b.HasOne("Bookify.Entities.Author", "Author")
                        .WithMany("Book")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bookify.Entities.Author", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
